### Expand kfo-apparatus-type
GET http://localhost:8080/ValueSet/kfo-apparatus-type/$expand
Authorization: Basic basic:secret

### Validate valid code festsitzend
GET http://localhost:8080/ValueSet/kfo-apparatus-type/$validate-code?system=https%3A%2F%2Ffhir.cognovis.de%2Fdental%2FCodeSystem%2Fkfo-apparatus-type&code=festsitzend
Authorization: Basic basic:secret

### Validate valid code herausnehmbar
GET http://localhost:8080/ValueSet/kfo-apparatus-type/$validate-code?system=https%3A%2F%2Ffhir.cognovis.de%2Fdental%2FCodeSystem%2Fkfo-apparatus-type&code=herausnehmbar
Authorization: Basic basic:secret

### Validate invalid code
GET http://localhost:8080/ValueSet/kfo-apparatus-type/$validate-code?system=https%3A%2F%2Ffhir.cognovis.de%2Fdental%2FCodeSystem%2Fkfo-apparatus-type&code=INVALID_XYZ_999
Authorization: Basic basic:secret
