### Expand periodontal-finding-codes
GET http://localhost:8080/ValueSet/periodontal-finding-codes/$expand
Authorization: Basic basic:secret

### Validate valid code 3877005
GET http://localhost:8080/ValueSet/periodontal-finding-codes/$validate-code?system=http%3A%2F%2Fsnomed.info%2Fsct&code=3877005
Authorization: Basic basic:secret

### Validate valid code LP96685-5
GET http://localhost:8080/ValueSet/periodontal-finding-codes/$validate-code?system=http%3A%2F%2Floinc.org&code=LP96685-5
Authorization: Basic basic:secret

### Validate invalid code
GET http://localhost:8080/ValueSet/periodontal-finding-codes/$validate-code?system=http%3A%2F%2Fsnomed.info%2Fsct&code=INVALID_XYZ_999
Authorization: Basic basic:secret
