### ValueSet: ProphylaxisFindingCodesVS - Expand
# VS URL: https://fhir.cognovis.de/dental/ValueSet/prophylaxis-finding-codes
# Expected: expansion.contains has 7 entries
GET http://localhost:8080/ValueSet/prophylaxis-finding-codes/$expand
Authorization: Basic basic:secret

### ValueSet: ProphylaxisFindingCodesVS - Validate Valid Code (18949003)
# System: http://snomed.info/sct
# Expected: result=true
GET http://localhost:8080/ValueSet/$validate-code?url=https://fhir.cognovis.de/dental/ValueSet/prophylaxis-finding-codes&system=http://snomed.info/sct&code=18949003
Authorization: Basic basic:secret

### ValueSet: ProphylaxisFindingCodesVS - Validate Valid Code (364126007)
# System: http://snomed.info/sct
# Expected: result=true
GET http://localhost:8080/ValueSet/$validate-code?url=https://fhir.cognovis.de/dental/ValueSet/prophylaxis-finding-codes&system=http://snomed.info/sct&code=364126007
Authorization: Basic basic:secret

### ValueSet: ProphylaxisFindingCodesVS - Validate Valid Code (8704-9)
# System: http://loinc.org
# Expected: result=true
GET http://localhost:8080/ValueSet/$validate-code?url=https://fhir.cognovis.de/dental/ValueSet/prophylaxis-finding-codes&system=http://loinc.org&code=8704-9
Authorization: Basic basic:secret

### ValueSet: ProphylaxisFindingCodesVS - Validate Valid Code (32953-2)
# System: http://loinc.org
# Expected: result=true
GET http://localhost:8080/ValueSet/$validate-code?url=https://fhir.cognovis.de/dental/ValueSet/prophylaxis-finding-codes&system=http://loinc.org&code=32953-2
Authorization: Basic basic:secret

### ValueSet: ProphylaxisFindingCodesVS - Validate Valid Code (32951-6)
# System: http://loinc.org
# Expected: result=true
GET http://localhost:8080/ValueSet/$validate-code?url=https://fhir.cognovis.de/dental/ValueSet/prophylaxis-finding-codes&system=http://loinc.org&code=32951-6
Authorization: Basic basic:secret

### ValueSet: ProphylaxisFindingCodesVS - Validate Invalid Code
# System: http://loinc.org
# Expected: result=false
GET http://localhost:8080/ValueSet/$validate-code?url=https://fhir.cognovis.de/dental/ValueSet/prophylaxis-finding-codes&system=http://loinc.org&code=INVALID_XYZ
Authorization: Basic basic:secret
