### Expand tooth-surfaces
GET http://localhost:8080/ValueSet/tooth-surfaces/$expand
Authorization: Basic basic:secret

### Validate valid code M
GET http://localhost:8080/ValueSet/tooth-surfaces/$validate-code?system=https%3A%2F%2Ffhir.cognovis.de%2Fdental%2FCodeSystem%2Ftooth-surfaces&code=M
Authorization: Basic basic:secret

### Validate valid code P
GET http://localhost:8080/ValueSet/tooth-surfaces/$validate-code?system=https%3A%2F%2Ffhir.cognovis.de%2Fdental%2FCodeSystem%2Ftooth-surfaces&code=P
Authorization: Basic basic:secret

### Validate invalid code
GET http://localhost:8080/ValueSet/tooth-surfaces/$validate-code?system=https%3A%2F%2Ffhir.cognovis.de%2Fdental%2FCodeSystem%2Ftooth-surfaces&code=INVALID_XYZ_999
Authorization: Basic basic:secret
