### ValueSet: ZeBefundkuerzelVS - Expand
# VS URL: https://fhir.cognovis.de/dental/ValueSet/ze-befundkuerzel
# Expected: expansion.contains has 50 entries
GET http://localhost:8080/ValueSet/ze-befundkuerzel/$expand
Authorization: Basic basic:secret

### ValueSet: ZeBefundkuerzelVS - Validate Valid Code (x)
# System: https://fhir.cognovis.de/dental/CodeSystem/ze-befundkuerzel
# Expected: result=true
# Actual: result=True
GET http://localhost:8080/ValueSet/$validate-code?url=https://fhir.cognovis.de/dental/ValueSet/ze-befundkuerzel&system=https://fhir.cognovis.de/dental/CodeSystem/ze-befundkuerzel&code=x
Authorization: Basic basic:secret

### ValueSet: ZeBefundkuerzelVS - Validate Valid Code (xb)
# System: https://fhir.cognovis.de/dental/CodeSystem/ze-befundkuerzel
# Expected: result=true
# Actual: result=True
GET http://localhost:8080/ValueSet/$validate-code?url=https://fhir.cognovis.de/dental/ValueSet/ze-befundkuerzel&system=https://fhir.cognovis.de/dental/CodeSystem/ze-befundkuerzel&code=xb
Authorization: Basic basic:secret

### ValueSet: ZeBefundkuerzelVS - Validate Invalid Code
# System: https://fhir.cognovis.de/dental/CodeSystem/ze-befundkuerzel
# Expected: result=false
# Actual: result=False
GET http://localhost:8080/ValueSet/$validate-code?url=https://fhir.cognovis.de/dental/ValueSet/ze-befundkuerzel&system=https://fhir.cognovis.de/dental/CodeSystem/ze-befundkuerzel&code=INVALID_XYZ
Authorization: Basic basic:secret
