### Test BemaBefundklasseCS - valid code c
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/bema-befundklasse&code=c
Authorization: Basic YmFzaWM6c2VjcmV0

### Test BemaBefundklasseCS - valid code k
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/bema-befundklasse&code=k
Authorization: Basic YmFzaWM6c2VjcmV0

### Test BemaBefundklasseCS - valid code f
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/bema-befundklasse&code=f
Authorization: Basic YmFzaWM6c2VjcmV0

### Test BemaBefundklasseCS - invalid code
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/bema-befundklasse&code=INVALID_XYZ
Authorization: Basic YmFzaWM6c2VjcmV0
