### CodeSystem: BEMA (Einheitlicher Bewertungsmaßstab Zahnärzte) - Valid Code '01'
GET http://localhost:8080/Concept?system=http://fhir.de/CodeSystem/kzbv/bema&code=01
Authorization: Basic basic:secret

### CodeSystem: BEMA (Einheitlicher Bewertungsmaßstab Zahnärzte) - Valid Code '04'
GET http://localhost:8080/Concept?system=http://fhir.de/CodeSystem/kzbv/bema&code=04
Authorization: Basic basic:secret

### CodeSystem: BEMA (Einheitlicher Bewertungsmaßstab Zahnärzte) - Invalid Code
GET http://localhost:8080/Concept?system=http://fhir.de/CodeSystem/kzbv/bema&code=INVALID_CODE_XYZ
Authorization: Basic basic:secret
