### Test GebuehrenordnungCS - valid code goae
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/gebuehrenordnung&code=goae
Authorization: Basic YmFzaWM6c2VjcmV0

### Test GebuehrenordnungCS - valid code goz
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/gebuehrenordnung&code=goz
Authorization: Basic YmFzaWM6c2VjcmV0

### Test GebuehrenordnungCS - invalid code
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/gebuehrenordnung&code=INVALID_XYZ
Authorization: Basic YmFzaWM6c2VjcmV0
