### Test KzvRegionenCS - valid code 01
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/kzv-regionen&code=01
Authorization: Basic YmFzaWM6c2VjcmV0

### Test KzvRegionenCS - valid code 02
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/kzv-regionen&code=02
Authorization: Basic YmFzaWM6c2VjcmV0

### Test KzvRegionenCS - valid code 03
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/kzv-regionen&code=03
Authorization: Basic YmFzaWM6c2VjcmV0

### Test KzvRegionenCS - invalid code
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/kzv-regionen&code=INVALID_XYZ
Authorization: Basic YmFzaWM6c2VjcmV0
