### Test PrivatgebuehrLeistungsartCS - valid code persoenlich
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/privatgebuehr-leistungsart&code=persoenlich
Authorization: Basic YmFzaWM6c2VjcmV0

### Test PrivatgebuehrLeistungsartCS - valid code technisch
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/privatgebuehr-leistungsart&code=technisch
Authorization: Basic YmFzaWM6c2VjcmV0

### Test PrivatgebuehrLeistungsartCS - invalid code
GET http://localhost:8080/Concept?system=https://fhir.cognovis.de/dental/CodeSystem/privatgebuehr-leistungsart&code=INVALID_XYZ
Authorization: Basic YmFzaWM6c2VjcmV0
