### Validate valid de-mira-dental-organization
POST http://localhost:8080/fhir/Organization/$validate?profile=https://fhir.cognovis.de/dental/StructureDefinition/de-mira-dental-organization
Authorization: Basic YWRtaW46YVZyeFA1TkJyZlRLZWlpdDBxRnpLVzNL
Content-Type: application/fhir+json

{
  "resourceType": "Organization",
  "id": "ExampleDentalOrganization",
  "meta": {
    "profile": [
      "https://fhir.cognovis.de/dental/StructureDefinition/de-mira-dental-organization"
    ]
  },
  "identifier": [
    {
      "system": "https://fhir.kbv.de/NamingSystem/KBV_NS_Base_BSNR",
      "value": "721234500"
    },
    {
      "system": "https://mira.cognovis.de/fhir/identifier/kzv-stempelnummer",
      "value": "K720001234"
    }
  ],
  "name": "Zahnarztpraxis Dr. Anna Mustermann",
  "type": [
    {
      "coding": [
        {
          "code": "prov",
          "system": "http://terminology.hl7.org/CodeSystem/organization-type",
          "display": "Healthcare Provider"
        }
      ]
    }
  ],
  "address": [
    {
      "use": "work",
      "type": "physical",
      "line": [
        "Maximilianstraße 42"
      ],
      "city": "München",
      "postalCode": "80538",
      "country": "DE"
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "+49 89 1234560",
      "use": "work"
    },
    {
      "system": "fax",
      "value": "+49 89 1234561",
      "use": "work"
    },
    {
      "system": "email",
      "value": "praxis@dr-mustermann-zahnarzt.de",
      "use": "work"
    }
  ]
}

### Validate invalid de-mira-dental-organization
# Expected: error - The property 'name' is required (min:1 in profile)
POST http://localhost:8080/fhir/Organization/$validate?profile=https://fhir.cognovis.de/dental/StructureDefinition/de-mira-dental-organization
Authorization: Basic YWRtaW46YVZyeFA1TkJyZlRLZWlpdDBxRnpLVzNL
Content-Type: application/fhir+json

{
  "resourceType": "Organization",
  "identifier": [
    {
      "system": "https://fhir.kbv.de/NamingSystem/KBV_NS_Base_BSNR",
      "value": "721234500"
    },
    {
      "system": "https://mira.cognovis.de/fhir/identifier/kzv-stempelnummer",
      "value": "K720001234"
    }
  ],
  "type": [
    {
      "coding": [
        {
          "code": "prov",
          "system": "http://terminology.hl7.org/CodeSystem/organization-type",
          "display": "Healthcare Provider"
        }
      ]
    }
  ],
  "address": [
    {
      "use": "work",
      "type": "physical",
      "line": [
        "Maximilianstraße 42"
      ],
      "city": "München",
      "postalCode": "80538",
      "country": "DE"
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "+49 89 1234560",
      "use": "work"
    }
  ]
}
