### Validate reordered six-site periodontal observation
POST http://localhost:8080/fhir/Observation/$validate?profile=https://fhir.cognovis.de/dental/StructureDefinition/periodontal-observation
Authorization: Basic YWRtaW46YVZyeFA1TkJyZlRLZWlpdDBxRnpLVzNL
Content-Type: application/fhir+json

< ../../fsh-generated/resources/Observation-ExamplePeriodontalObservationReordered.json

### Validate canonical mobility without suppuration
POST http://localhost:8080/fhir/Observation/$validate?profile=https://fhir.cognovis.de/dental/StructureDefinition/periodontal-observation
Authorization: {{$processEnv AIDBOX_AUTH}}
Content-Type: application/fhir+json

< ../../fsh-generated/resources/Observation-ExamplePeriodontalObservation.json

### Validate canonical mobility with site-identified suppuration
POST http://localhost:8080/fhir/Observation/$validate?profile=https://fhir.cognovis.de/dental/StructureDefinition/periodontal-observation
Authorization: {{$processEnv AIDBOX_AUTH}}
Content-Type: application/fhir+json

< ../../fsh-generated/resources/Observation-ExamplePeriodontalObservationPAR.json

### Reject periodontal observation without required status and subject
POST http://localhost:8080/fhir/Observation/$validate?profile=https://fhir.cognovis.de/dental/StructureDefinition/periodontal-observation
Authorization: Basic YWRtaW46YVZyeFA1TkJyZlRLZWlpdDBxRnpLVzNL
Content-Type: application/fhir+json

{
  "resourceType": "Observation",
  "meta": {
    "profile": [
      "https://fhir.cognovis.de/dental/StructureDefinition/periodontal-observation"
    ]
  },
  "code": {
    "coding": [
      {
        "system": "http://loinc.org",
        "code": "8704-9"
      }
    ]
  },
  "bodySite": {
    "coding": [
      {
        "system": "https://fhir.cognovis.de/dental/CodeSystem/tooth-identification-fdi",
        "code": "16"
      }
    ]
  },
  "component": [
    {
      "extension": [
        {
          "url": "https://fhir.cognovis.de/dental/StructureDefinition/periodontal-measurement-site",
          "valueCodeableConcept": {
            "coding": [
              {
                "system": "https://fhir.cognovis.de/dental/CodeSystem/periodontal-measurement-site",
                "code": "mesiobuccal"
              }
            ]
          }
        }
      ],
      "code": {
        "coding": [
          {
            "system": "http://loinc.org",
            "code": "32884-9"
          }
        ]
      },
      "valueQuantity": {
        "value": 5,
        "system": "http://unitsofmeasure.org",
        "code": "mm"
      }
    }
  ]
}
