### Validate an avulsion observation
POST http://localhost:8080/fhir/Observation/$validate?profile=https://fhir.cognovis.de/dental/StructureDefinition/trauma-observation
Authorization: Basic basic:secret
Content-Type: application/fhir+json

< ../../fsh-generated/resources/Observation-ExampleAvulsionObservation11.json

### Validate one finding from a combined injury event
POST http://localhost:8080/fhir/Observation/$validate?profile=https://fhir.cognovis.de/dental/StructureDefinition/trauma-observation
Authorization: Basic basic:secret
Content-Type: application/fhir+json

< ../../fsh-generated/resources/Observation-ExampleCombinedLateralLuxation21.json
